### ISSUE TITLE
App Group issues

### ISSUE THREAD

**Issue by brettohland** [FancyPixel/gulps#2]
The App Group identifier needs to be unique (which is why Apple recommends using reverse domain style names). Since group.it.fancypixel.BigGulp is taken, you might want to just remove the app groups all together and add instructions to set up your own (probably also need to break the hardcoded `group.it.fancypixel.BigGulp` our and place them in a config or external constant file).

Because the App Group won't be set up by default, this causes a crash on line 5 of the EntryHandler.swift file since the app group container is an optional and will try to unwrap nil.

``` Swift
let directory: NSURL = NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("group.it.fancypixel.BigGulp")!
```

A beginner, trying to run the app, might be confused as to why this is happening.

**Comment by andreamazz** [comment]
Hi @brettohland 
That's a good point, I'm currently moving some hardcoded stuff out to `cocoapods-keys`, so we'll be able to deploy directly from this repo while sharing it here with ease. 
I'll also make sure to update the setup instructions.  

Thanks for the feedback. 
Cheers :beers:

**Comment by Isuru-Nanayakkara** [comment]
+1

**Comment by andreamazz** [comment]
Hi all. 
I've added a script in the latest commit that changes all the bundle identifiers in the project. You just need to run it: 
```
bundle
ruby change_bundle.rb your.bundle.app
```
Then you can change the bundle in the `Constants.swift` file. That should pretty much cover it. Let me know if that works.

**Comment by Isuru-Nanayakkara** [comment]
Followed your steps. But I get the following error when running.

**fatal error: Unable to setup Realm. Make sure to setup your app group in the developer portal**

**Comment by andreamazz** [comment]
Hi @Isuru-Nanayakkara 
Did you create the app group on your developer portal? I double checked the script that changes the plists and entitlements, and it should be working fine.
Make sure to create the group in your dev portal and then double check in the project settings that the group is actually enabled in the capabilities section.

**Comment by Isuru-Nanayakkara** [comment]
Oh I see. I currently don't have developer account. So I guess I won't be able to test it right now.

**Comment by andreamazz** [comment]
Sadly no, to use app groups a developer account is required as far as I know.

**Comment by qrodgers13** [comment]
Sorry for commenting on a closed issue but I created an app group, verified that the group is enabled in the capabilities section and I'm still getting the "fatal error: Unable to setup Realm. Make sure to setup your app group in the developer portal". 

Any other suggestions?

**Comment by andreamazz** [comment]
Hi @qrodgers13 
Did you make sure that the group id is enabled in your developer portal? Also, make sure that the bundle matches when running the `change_bundle` ruby script

**Comment by qrodgers13** [comment]
Thanks @andreamazz. I was able to figure it out - it appears that under Targets > "Build Settings" > "Product Bundle Identifier" wasn't updated to my bundle and still had the it.fancypixel.BigGulp. 

Not sure if this was my error but wanted to share in case anyone else ran into the same issue.

**Comment by IonutBBB** [comment]
Hi @andreamazz , thanks for the resource. do you have any idea why I get this error: "Value of type 'Realm' has no member 'addNotificationBlock'

I get this in TodayViewControler at line 27:
 realmToken = EntryHandler.sharedHandler.realm.addNotificationBlock { note, realm in
      self.updateUI()
    }

Thank you
